### ISSUE TITLE
Missing Version on PyPI

### ISSUE THREAD

**Issue by ivan-c** [fmoo/python-editor#13]
Hi,
Version 1.0.2 [appears to be missing on PyPI](https://pypi.python.org/simple/python-editor/).

I'm not familiar with publishing on PyPI, but was 1.0.2 ever released or does the "latest" version need to be set to 1.0.2b?

Thank you!

**Comment by di** [comment]
Same here:

```
$ pip install python-editor==1.0.2
Collecting python-editor==1.0.2
  Could not find a version that satisfies the requirement python-editor==1.0.2 (from versions: 0.1, 0.3, 0.4, 0.5, 1.0, 1.0.1, 1.0.2b0)
No matching distribution found for python-editor==1.0.2
```

**Comment by fmoo** [comment]
Yeah I kinda fucked it up by accidentally uploading 1.0.2 to the 1.0.1 page.  I removed it but pypi doesn't let you upload a file with the same name to a different page, regardless of whether it actually exists or not....

I can scrap 1.0.2 and try a 1.0.3 if it helps?

**Comment by ivan-c** [comment]
Let me reiterate that I'm not very familiar with PyPI, but releasing a new version should fix the issue in my limited use case ([pyup.io](https://pyup.io/) automatic PRs).

**Comment by fmoo** [comment]
Ok, I just bumped the version again to 1.0.3 and messed with my .pypirc some more and everything uploaded correctly this time around.  lmk

**Comment by di** [comment]
Thanks @fmoo!

**Comment by ivan-c** [comment]
Works for me, thanks again @fmoo!
