### ISSUE TITLE
Include README and LICENSE file in pypi tarball.

### ISSUE THREAD

**Issue by chkumar246** [fmoo/python-editor#3]
we are packaging python-editor for fedora. As per the pypi tarball : https://pypi.python.org/pypi/python-editor , the README and LICENSE file is missing. Please include in the pypi tarball and version tag is also missing on github. Please include it.

**Comment by fmoo** [comment]
Any preference as to whether I do a minor version bump for this or not?  I would prefer to.

**Comment by chkumar246** [comment]
@fmoo Thanks for quick reply. Please do a minor version bump.
I have added a patch for including README.md and LICENSE file also. https://github.com/fmoo/python-editor/pull/2
Please have a look.

**Comment by fmoo** [comment]
Yep.  PR has been merged and 0.4 tarball has been pushed to pypi.
