### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by eugene-eeo** [fmoo/python-editor#7]
Not a "real" issue, just thought about dropping by to say thank you for such an easy-to-use module. :+1:

**Comment by fmoo** [comment]
You're welcome!

What are you using it for if I might ask?

**Comment by eugene-eeo** [comment]
https://github.com/eugene-eeo/takeit to help users select the files. Originally I was using inquirer and had a fancy checkbox, but for file lists which are too long the UI is just abysmal (my fault though).

**Comment by fmoo** [comment]
Cool.  Glad it's useful!
