### ISSUE TITLE
Open editor with line number?

### ISSUE THREAD

**Issue by farridav** [fmoo/python-editor#9]
Great work BTW...

I'm hoping to use this for a nose plugin I'm writing, but id like to pass a line number through to the editor command... Any chance you could expose that? or better still allow arbitrary args to be passed through?

e.g. `emacs +123`

Thanks

**Comment by davidparsson** [comment]
As far as I know, there's no common command line API for opening a file on a specific line, so I don't see how this can work with all editors. However, I do know some editors support appending the row and column number to paths like this `file:<row>:<col>`, e.g. `file:30:10`.
